function trackHistoryTable = trackHistoryToTable(trackHistory)

trackHistoryTable = table('Size', [3, 19], 'VariableTypes', {'table', 'table', 'table', 'table', 'table', ...
    'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', ...
    'doubleNaN', 'doubleNaN', 'table', 'table', 'doubleNaN', 'doubleNaN', 'table', 'table'}, ...
    'VariableNames', {'Posterior', 'RawMeasurements', 'RawOrientations', 'MeasIndex', ...
    'Prediction', 'PredictedX', 'LinePredictedX', 'LastAngle', 'LastVelocity', ...
    'StartTime', 'EndTime', 'LastSeenTime', 'TrueIntersection', 'Length', 'Width', ...
    'PredictedIntersectionTime', 'LinepredictedIntersectionTime', 'OrientationEstimates', ...
    'VisualClassifications'});

trackHistoryTable.Posterior = [(trackHistory(1).StartTime:trackHistory(1).StartTime + size(trackHistory(1).Posterior, 2) - 1); trackHistory(1).Posterior]';

end