name: Run MATLAB Tests on GitHub-Hosted Runner

permissions: read-all

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Checkout, Compile and Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Check out TracksortAlgorithm repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: List all files up to depth 4
        run: |
          find . -maxdepth 4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: Image_Processing_Toolbox Statistics_and_Machine_Learning_Toolbox Symbolic_Math_Toolbox Parallel_Computing_Toolbox Deep_Learning_Toolbox

      - name: Add lib directory to path and compile
        uses: matlab-actions/run-command@v2
        with:
          command: "addpath(genpath('External/libDirectional')); compileAll;"

      - name: Run tests in TracksortAlgorithm/Tests
        uses: matlab-actions/run-tests@v2
        with:
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
          select-by-folder: Tests
          source-folder: Tracking; External

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-results/results.xml
